### ISSUE TITLE
Automate build/deploy

### ISSUE THREAD

**Issue by pgmmpk** [YinlinHu/pypdfium#1]
pdfium-binaries are re-built every Monday, automatically (with Travis and Appveyor). Would be nice to make pypdfium follow the same pattern and automatically build and release (every Tuesday?).

Script should do the following:
1. Find out the latest tag
   ```bash
   git ls-remote --heads https://github.com/bblanchon.pdfium-binaries.git | grep -ohP 'chromium/\d+'  | tail -n1`
   ```
2. build download URLs for each platform, download binaries
3. extract binaries
4. run `ctypesgen` on extracted lib and headers
5. commit binaries and python wrapper
6. build wheel
7. deploy to PyPi

**Comment by YinlinHu** [comment]
Sounds great. Will have a closer look later.

**Comment by mara004** [comment]
Done, except for point 7
