### ISSUE TITLE
bblanchon/pdfium-binaries now uses `pdfium-linux-x64.tgz` instead of `pdfium-linux.tgz` as the linux binary archive name

### ISSUE THREAD

**Issue by adam-huganir** [YinlinHu/pypdfium#5]
This appears to have just switched over as of the latest build, from `chromium/4655`. This will cause the `update_bindings.py` file to fail with a 404 error

I will update the `update_bindings.py` file with the new name.

**Comment by adam-huganir** [comment]
They seem to have switched the windows dll compression from zip to tgz as well, changing the filename. Updated branch at
https://github.com/adam-huganir/pypdfium/tree/issues/5-bblanchon/pdfium-binaries-now-uses-pdfium-linux-x64

I cannot currently test mac/windows builds, so I am not putting the PR yet. I should be able to test later tonight.

**Comment by adam-huganir** [comment]
Windows  does not work in the current master (subprocess uses linux stile pipe operators `|`) but that is an issue for another time.

**Comment by adam-huganir** [comment]
PR in https://github.com/YinlinHu/pypdfium/pull/7

**Comment by YinlinHu** [comment]
Thanks a lot. Just merged.
